spring:
  profiles:
    active: oauth
    include: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa: #jpa 종류
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql : true #콘솔에 로그가 나옴
        format_sql: true #이쁘게 해줌
  redis:
    host: localhost
    port: 6379

logging.level:
  root: info
  org.hibernate.SQL: trace #콘솔에 남기는게 아니라 로그로 남음.
  org.hibernate.type: trace #바인딩된 파라미터까지 볼 수 있