## This workflow uses actions that are not certified by GitHub.
## They are provided by a third-party and are governed by
## separate terms of service, privacy policy, and support
## documentation.
## This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
## For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/checkout@master
      - uses: pustovitDmytro/redis-github-action@v1.0.1
      - uses: ankane/setup-mariadb@v1
      - name: Create DB, DB user, grant permission
        run: |
              sudo mysql -e "create database if not exists ${{ secrets.DB_NAME}}"
              sudo mysql -e "create user '${{ secrets.DB_USER_NAME}}'@localhost identified by '${{ secrets.DB_USER_PASSWORD}}'"
              sudo mysql -e "grant all privileges on ${{ secrets.DB_NAME}}.* to '${{ secrets.DB_USER_NAME}}'@localhost"
      - name: read repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create application-oauth.yml
        run: |
              echo -e "${{ secrets.APPLICATION_OAUTH}}" >> ./src/main/resources/application-oauth.yml
              echo -e "${{ secrets.APPLICATION_PROD}}" >> ./src/main/resources/application-prod.yml
              sed -i '0,/dev/s//prod/' ./src/main/resources/application.yml
      - name: Build with Gradle
        run: ./gradlew clean build  --stacktrace